export enum TournamentStatus {
  REGISTRATION_OPEN = 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED = 'REGISTRATION_CLOSED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  SCHEDULED = 'SCHEDULED',
}

export enum TournamentDivision {
  DIVISION_I = 'DIVISION_I',
  DIVISION_II = 'DIVISION_II',
  DIVISION_III = 'DIVISION_III',
}
