import { BadRequestException, Injectable, Logger } from '@nestjs/common';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { CountryDto } from './dto/location.dto';

/**
 * Countries that are never offered to players and are rejected on write
 * (ISO 3166-1 alpha-2). Kept server-side so the rule holds regardless of client.
 * Mirrored in scripts/build-locations.py so the data never contains them either.
 */
export const EXCLUDED_COUNTRY_CODES: ReadonlySet<string> = new Set([
  'RU', // Russia
  'BY', // Belarus
  'IR', // Iran
]);

/**
 * Bundled catalog generated by `scripts/build-locations.py` from GeoNames
 * (countryInfo + cities1000 + Ukrainian alternate names). Copied into `dist`
 * by the `assets` entry in nest-cli.json, so `__dirname` works for both ts-node
 * and the compiled build.
 */
const DATA_DIR = join(__dirname, 'data');

/**
 * Location catalogs for the profile picker (country → city). Everything is
 * served from the bundled JSON — no third-party API at runtime, so the picker
 * cannot break or fall back to English when an external service is down.
 * City names are Ukrainian wherever GeoNames has a `uk` alternate name.
 */
@Injectable()
export class LocationsService {
  private readonly logger = new Logger(LocationsService.name);

  private countriesCache: CountryDto[] | null = null;
  private readonly citiesCache = new Map<string, string[]>();

  static normalizeCountryCode(code: string): string {
    return code.trim().toUpperCase();
  }

  static isExcludedCountry(code: string): boolean {
    return EXCLUDED_COUNTRY_CODES.has(
      LocationsService.normalizeCountryCode(code),
    );
  }

  /** Allowed countries sorted by English name (the client localizes via Intl). */
  async getCountries(): Promise<CountryDto[]> {
    if (this.countriesCache) return this.countriesCache;

    const raw = await readFile(join(DATA_DIR, 'countries.json'), 'utf8');
    const rows = JSON.parse(raw) as CountryDto[];
    const seen = new Set<string>();
    const countries: CountryDto[] = [];
    for (const row of rows) {
      const code = LocationsService.normalizeCountryCode(row.code ?? '');
      const name = (row.name ?? '').trim();
      if (!/^[A-Z]{2}$/.test(code) || !name) continue;
      if (EXCLUDED_COUNTRY_CODES.has(code) || seen.has(code)) continue;
      seen.add(code);
      countries.push({ code, name });
    }
    countries.sort((a, b) => a.name.localeCompare(b.name, 'en'));
    this.countriesCache = countries;
    return countries;
  }

  /** Cities of one allowed country (by ISO alpha-2), sorted for Ukrainian collation. */
  async getCities(countryCode: string): Promise<string[]> {
    const code = LocationsService.normalizeCountryCode(countryCode);
    const country = await this.findCountry(code);
    if (!country) {
      throw new BadRequestException('Невідома або недоступна країна');
    }

    const cached = this.citiesCache.get(code);
    if (cached) return cached;

    let names: string[] = [];
    try {
      const raw = await readFile(
        join(DATA_DIR, 'cities', `${code}.json`),
        'utf8',
      );
      const parsed = JSON.parse(raw) as unknown;
      if (Array.isArray(parsed)) {
        names = parsed.filter((n): n is string => typeof n === 'string');
      }
    } catch (err) {
      // No file means the country has no places above the dataset threshold.
      if ((err as NodeJS.ErrnoException)?.code !== 'ENOENT') {
        this.logger.warn(`Cities file unreadable for ${code}`, err);
      }
    }

    const unique = [...new Set(names.map((n) => n.trim()).filter(Boolean))];
    unique.sort((a, b) => a.localeCompare(b, 'uk'));
    this.citiesCache.set(code, unique);
    return unique;
  }

  /** Resolves a code against the allowed catalog; `null` when unknown or excluded. */
  async findCountry(countryCode: string): Promise<CountryDto | null> {
    const code = LocationsService.normalizeCountryCode(countryCode);
    if (LocationsService.isExcludedCountry(code)) return null;
    const countries = await this.getCountries();
    return countries.find((c) => c.code === code) ?? null;
  }
}
